@startuml Components

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites
!includeurl SPRITESURL/ethers.puml
!includeurl SPRITESURL/ethereum.puml



rectangle "BuyTokens" {
  [BuyTokens] --> [LoadBlockchainData] : <<use>>

  [LoadBlockchainData] *-right-> [DappToken <$ethereum> ] : contains <$ethereum>
  [LoadBlockchainData] *-right-> [DappTokenSale] : contains
  [LoadBlockchainData] *-right-> [Transactions] : contains
  [LoadBlockchainData] *-right-> [AirDrop] : contains

  [LoadBlockchainData] --* [DappToken] : uses
  [LoadBlockchainData] --* [DappTokenSale] : uses
  [LoadBlockchainData] --* [Transactions] : uses
  [LoadBlockchainData] --* [AirDrop] : uses

  [LoadBlockchainData] -[hidden]-> [ethers.BrowserProvider] : uses
  [LoadBlockchainData] -[hidden]-> [ethers.Contract] : uses
  [LoadBlockchainData] -[hidden]-> [ethers.Signer] : uses
}

[BuyTokens] --> [ethers.BrowserProvider] : uses
[BuyTokens] -[hidden]-> [ethers.Contract] : uses
[BuyTokens] -[hidden]-> [ethers.toBigInt] : uses
[BuyTokens] -[hidden]-> [ethers.BrowserProvider] : uses
[BuyTokens] -[hidden]-> [LoadLogo] : uses
[BuyTokens] -[hidden]-> [Swap] : uses
[BuyTokens] -[hidden]-> [Transfer] : uses

[LoadLogo] -[hidden]-> [DappToken] : uses



@enduml
