@startuml

!define RECTANGLE class
!define RECTANGLE2 component
!define INTERFACE interface

RECTANGLE2 App {
}

RECTANGLE LoadWeb3 {
  - addressProvider: string
  - isLoading: boolean
  - loadingInfo: string
  + useEffect()
  + loadWeb3()
}

RECTANGLE LoadingScreen {
  - loadingInfo: string
}

RECTANGLE LoadBlockchainData {
  - addressProvider: string
}

RECTANGLE2 Background {
}

RECTANGLE EthereumService {
  + checkAccountChange()
}

INTERFACE ethers.BrowserProvider
INTERFACE ethers.Signer
INTERFACE window.ethereum

App --> LoadWeb3
LoadWeb3 --> LoadingScreen :używa
LoadWeb3 --> LoadBlockchainData :używa
LoadWeb3 --> Background :używa
LoadWeb3 --> EthereumService :używa

LoadWeb3 --> ethers.BrowserProvider: tworzy
LoadWeb3 --> ethers.Signer: tworzy

EthereumService --> window.ethereum: nasłuchuje

@enduml
