@startuml

!define RECTANGLE class

namespace User {
    class User
}

namespace Wallet {
    class Wallet
}

namespace Browser {
    class Browser
}

namespace FrontEnd {
    class HTML
    class CSS
    class JavaScript
    class React
}

namespace BackEnd {
    class Node
}

namespace SmartContract {
    class Solidity
}

User.User --> Wallet.Wallet : "Performs Transactions"
Wallet.Wallet --> Browser.Browser : "Manages Wallet"
Browser.Browser --> FrontEnd.HTML : "Renders"
Browser.Browser --> FrontEnd.CSS : "Styles"
Browser.Browser --> FrontEnd.JavaScript : "Interactivity"
FrontEnd.HTML --> FrontEnd.React : "Composes"
FrontEnd.CSS --> FrontEnd.React : "Composes"
FrontEnd.JavaScript --> FrontEnd.React : "Composes"
FrontEnd.React --> BackEnd.Node : "Sends Data"
BackEnd.Node --> SmartContract.Solidity : "Processes Transactions"

note right of Wallet.Wallet :  Zarządza\n środkami użytkownika
note right of FrontEnd.React :  Zarządza\n stanem komponentów UI

@enduml
