@startuml SmartContractAction


SmartContractA -> SmartContractB: interakcja z ContractB

SmartContractB: wykonuje zapytanie

SmartContractB -> SmartContractA: zwraca odpowiedź

SmartContractA: reaguje na odpowiedź


@enduml
