@startuml
[*] --> LoadingData : Start

state LoadingData {
  [*] --> CheckWeb3 : Check Web3
  CheckWeb3 --> Web3 Available LoadWeb3 : Web3 Available
  CheckWeb3 --> |Web3 Unavailable| Error : Web3 Unavailable
  LoadWeb3 --> |Success| LoadBlockchainData : Load Web3 Success
  LoadWeb3 --> |Error| Error : Load Web3 Failed
  LoadBlockchainData --> |Success| Loaded : Data Loaded Successfully
  LoadBlockchainData --> |Error| Error : Load Data Failed
  Loaded --> [*] : Restart
  Error --> [*] : Restart
}

state LoadWeb3 {
  --> [*] : Start
}

state LoadBlockchainData {
  --> [*] : Start
}

state Loaded {
  --> [*] : Start
}

state Error {
  --> [*] : Start
}

[*] --> LoadingData : Restart
@enduml
