@startuml Kup
actor Investor

usecase "Enter Application" as Step1
usecase "Login to MetaMask" as Step2
usecase "Select Purchase Section" as Step3
usecase "Select Token Quantity" as Step4
usecase "Press Buy Button" as Step5
usecase "Confirm ETH Payment" as Step6
usecase "Assign Tokens to Wallet" as Step7

Investor --> Step1 : "Step 1"
Step1 --> Step2 : "Step 2"
Step2 --> Step3 : "Step 3"
Step3  --> Step4 : "Step 4"
Step4 --> Step5 : "Step 5"
Step5 --> Step6 : "Step 6"
Step6 --> Step7 : "Step 7"
Step7 --> Investor
@enduml
